In [4]:
import numpy as np
import torch
import torch.nn as nn

y_preds = []
labels = []

weights = torch.tensor([1.0, 2.0, 4.0])
criterion2 = nn.CrossEntropyLoss(weight=weights)

for i in range(1):
    try:
        pred = torch.from_numpy(np.load(f'/Users/markun/git/rsna2024/kaggle/outputs/preds_fold{i}.npy'))
        label = torch.from_numpy(np.load(f'/Users/markun/git/rsna2024/kaggle/outputs/labels_fold{i}.npy'))
        y_preds.extend(pred)
        labels.extend(label)
    except:
        raise RuntimeError('File Not Found')

y_preds = torch.cat(y_preds)
labels = torch.cat(labels)
print(y_preds)
print(labels)

cv = criterion2(y_preds, labels)
print('cv score:', cv.item())

tensor([[ 1.9685e-01, -1.2119e-01, -1.6247e-01],
        [ 1.8895e-01, -1.8935e-01, -2.9064e-01],
        [ 3.1785e-02,  4.0191e-02, -1.2160e-01],
        [ 8.8336e-02, -1.0261e-01,  2.9734e-02],
        [ 2.9508e-01, -2.4096e-01, -2.2420e-01],
        [ 6.9074e-02, -8.9567e-02, -7.4414e-02],
        [ 1.2610e-01, -1.2364e-01, -3.9427e-02],
        [ 1.4523e-01,  1.6749e-01, -6.5555e-02],
        [-3.8271e-02, -6.8111e-02, -1.1017e-01],
        [ 1.2143e-01,  4.0516e-02, -9.2817e-02],
        [ 1.3047e-01, -1.7844e-02, -2.9385e-02],
        [ 1.6482e-01, -8.8431e-02,  5.8801e-03],
        [ 1.6625e-01, -3.3224e-02, -1.5848e-03],
        [ 5.4904e-02,  1.0949e-01, -4.9129e-02],
        [ 1.1897e-01,  2.0863e-01, -5.9711e-02],
        [ 4.9764e-02, -2.0313e-01, -8.1219e-02],
        [ 2.4195e-01, -2.1078e-01, -1.1635e-01],
        [ 5.6704e-02,  2.0907e-01, -1.1785e-01],
        [-3.4953e-02,  9.8102e-04,  1.4022e-01],
        [ 1.6431e-01, -1.3798e-01,  6.5664e-03],
        [ 2.4948e-01

In [7]:
from sklearn.metrics import log_loss
y_pred_np = y_preds.softmax(1).numpy()
labels_np = labels.numpy()
y_pred_nan = np.zeros((y_preds.shape[0], 1))
#y_pred2 = np.concatenate([y_pred_nan, y_pred_np],axis=1)
weights = []
for l in labels:
    if l==0: weights.append(1)
    elif l==1: weights.append(2)
    elif l==2: weights.append(4)
    else: weights.append(0)
print(y_pred_np)
print(labels)
cv2 = log_loss(labels, y_pred_np, normalize=True, sample_weight=weights)
print('cv score:', cv2)

[[0.4122486  0.29994076 0.28781065]
 [0.4340162  0.29731107 0.2686727 ]
 [0.34888947 0.35183436 0.2992762 ]
 [0.36110783 0.2983379  0.3405542 ]
 [0.45871282 0.26837522 0.27291188]
 [0.36769664 0.31375635 0.31854692]
 [0.3807424  0.29659858 0.322659  ]
 [0.35305038 0.36099756 0.28595206]
 [0.34468216 0.3345491  0.32076874]
 [0.3663782  0.33790037 0.29572147]
 [0.36840257 0.31762108 0.3139764 ]
 [0.38032585 0.29523745 0.32443672]
 [0.37528232 0.30741787 0.31729987]
 [0.33814678 0.3571169  0.30473638]
 [0.34127638 0.37328896 0.2854347 ]
 [0.3768211  0.29261932 0.3305596 ]
 [0.4283118  0.2723575  0.29933077]
 [0.33284366 0.38762414 0.27953222]
 [0.30978587 0.32112014 0.36909398]
 [0.38562447 0.28502423 0.3293513 ]
 [0.41626924 0.29352427 0.2902064 ]
 [0.42387575 0.3049775  0.27114674]
 [0.44791114 0.26014084 0.29194802]
 [0.2969462  0.40655884 0.29649493]
 [0.33269525 0.3772581  0.29004672]
 [0.41241968 0.30001238 0.2875679 ]
 [0.4347089  0.29686102 0.26843005]
 [0.34833404 0.35131776 0.30